### ISSUE TITLE
Random letters appear

### ISSUE THREAD

**Issue by noisycat05** [BackRoom-net/Backroom-net#14]
https://github.com/BackRoom-net/Backroom-net/blob/c9b5304dbe2039a6d51f3d2889783952c9ae5c96/Code/Application/Backroom.pb#L390

Its odd, compile the program and try to make a package of anything. as you see the files being processed, you may see random Letters appear at the end of the message. 

I think it may be caused by me not Running my strings correctly and getting the difference right. hey, @crodzilla ? You think you could take a look? I marked the line of the checker above. all it does it replaces the string of that specific line.

**Comment by crodzilla** [comment]
# Fixed issue
